main: com.shyndard.over2craft.wonderbuild.MainPlugin
name: Wonderbuild
version: "1.0.0"
description: Wonderbuild plugin
author: shyndard
commands:
   tb:
      description: Wonderbuild's command
      usage: /<command> <setspawn> <guesser|builder>
      permission: wonderbuild.admin
api-version: 1.16